[package]
name = "qcpu"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
enum_properties = "0.3.0"
strum.workspace = true
strum_macros.workspace = true
qcpu_assembler.workspace = true
qcpu_simulator.workspace = true
qcpu_syntax.workspace = true
