[workspace]
members = ["qcpu", "qcpu_assembler"]
resolver = "2"
default-members = ["qcpu"]


[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
clap = { version = "4.5.19", features = ["derive"] }

strum = "0.26.3"
strum_macros = "0.26.4"
nom = "7.1.3"

qcpu_assembler = { path = "./qcpu_assembler" }
