[package]
name = "qcpu_syntax"
version.workspace = true
edition.workspace = true

[dependencies]
strum.workspace = true
strum_macros.workspace = true
nom.workspace = true
bitvec.workspace = true
enum_properties.workspace = true
